// Generated by CoffeeScript 1.9.2
module.exports = function(map) {
  if (map == null) {
    map = {};
  }
  return {
    set: function(key, value) {
      return map[key] = value;
    },
    get: function(key) {
      return map[key];
    },
    clear: function(key) {
      return delete map[key];
    },
    length: function() {
      return Object.keys(map).length;
    },
    all: function() {
      return map;
    }
  };
};
