// Generated by CoffeeScript 1.9.2
var ShulzMapCorrupt, fs, markers, roundbyte;

fs = require('graceful-fs');

markers = require('./markers');

roundbyte = require('./roundbyte');

ShulzMapCorrupt = require('./errors').ShulzMapCorrupt;

module.exports = function(path) {
  var buffer, key, keylength, marker, offset, result, value, valuelength;
  result = {};
  buffer = fs.readFileSync(path);
  offset = 0;
  while (offset < buffer.length) {
    marker = buffer.readUInt32BE(offset);
    offset += 4;
    if (marker === markers.noop) {
      break;
    }
    if (marker === markers.set) {
      keylength = buffer.readUInt32BE(offset);
      offset += 4;
      key = buffer.toString('utf8', offset, offset + keylength);
      offset += keylength;
      offset = roundbyte(offset);
      valuelength = buffer.readUInt32BE(offset);
      offset += 4;
      value = buffer.toString('utf8', offset, offset + valuelength);
      offset += valuelength;
      offset = roundbyte(offset);
      result[key] = value;
    } else if (marker === markers.clear) {
      keylength = buffer.readUInt32BE(offset);
      offset += 4;
      key = buffer.toString('utf8', offset, offset + keylength);
      offset += keylength;
      offset = roundbyte(offset);
      delete result[key];
    } else {
      throw new ShulzMapCorrupt();
    }
  }
  return result;
};
